### ISSUE TITLE
The output tensor's shape of SwinOp is not correct.

### ISSUE THREAD

**Issue by MenglingD** [NVIDIA/FasterTransformer#272]
### Description

The output tensor's shape is：[bs, img_size * img_size, in_chans] describe in: [src/fastertransformer/th_op/swin/SwinOp.h#L198](https://github.com/NVIDIA/FasterTransformer/blob/main/src/fastertransformer/th_op/swin/SwinOp.h#L198):

```c++
          std::vector<ft::Tensor> output_tensors = std::vector<ft::Tensor>{
                 ft::Tensor{ft::MEMORY_GPU,
                                  data_type,
                                  std::vector<size_t>{(size_t)batch_size, (size_t)img_size_ * img_size_, (size_t)in_chans_},
                                  get_ptr<T>(output)}};
```

which is match the shape described by [src/fastertransformer/models/swin/Swin.cc#L175](https://github.com/NVIDIA/FasterTransformer/blob/main/src/fastertransformer/models/swin/Swin.cc#L175): [bs, final_len]:

```c++
           // input_tensors:
           //      input_images [batch, in_channels, input_resolution, input_resolution]
           //      sm [1]
           // output_tensors:
           //      output_embedding [batch, final_len]
```

### Reproduced Steps

```shell
no need reproduced steps
```

**Comment by byshiue** [comment]
Hi, MenglinD. Thank you for the catching. The shape of [src/fastertransformer/th_op/swin/SwinOp.h#L198](https://github.com/NVIDIA/FasterTransformer/blob/main/src/fastertransformer/th_op/swin/SwinOp.h#L198) is wrong, it should be output_dim_ calculated in the op. It does not lead to wrong results, but mislead the code reading.
Because next release is close, we will fix it at the time.
