### ISSUE TITLE
docker/Dockerfile.torch occurs errors

### ISSUE THREAD

**Issue by b3y0nd** [NVIDIA/FasterTransformer#720]
### Branch/Tag/Commit

main

### Docker Image Version

nvcr.io/nvidia/pytorch:22.09-py3

### GPU name

RTX 3060ti

### CUDA Driver

525.116.04

### Reproduced Steps

```shell
when run git submodule update --init --recursive in Dockerfile.torch line 34, the errors occurs:fatal: not a git repository (or any of the parent directories): .git. This is because the current folder is not a Git project folder. Consider deleting it or adjusting your code to resolve this issue.
```

**Comment by duongkstn** [comment]
Same issue. Any updates ?

**Comment by duongkstn** [comment]
Hi, may be I know how to tackle your issue.
It might be due to your path (when typing `docker build`) was wrong.
  In more details, my issue appear when I was in folder `FasterTransformer/docker` and typed `sudo docker build -t ft -f Dockerfile.torch`


But then I changed folder path to `FasterTransformer` and typed `sudo docker build -t ft -f ./docker/Dockerfile.torch`, the issue disappeared !

Hope this helps !

**Comment by b3y0nd** [comment]
> Hi, may be I know how to tackle your issue. It might be due to your path (when typing `docker build`) was wrong. In more details, my issue appear when I was in folder `FasterTransformer/docker` and typed `sudo nvidia-docker build -t ft -f Dockerfile.torch .`
> 
> But then I changed folder path to `FasterTransformer` and typed `sudo nvidia-docker build -t ft -f ./docker/Dockerfile.torch .`, the issue disappeared !
> 
> Hope this helps !

thanks for your reply. I'll try later

**Comment by thusinh1969** [comment]
So buggy ! Still can not build Docker, this error leads to another...!
