### ISSUE TITLE
gpt tf op request_input_len and max_input_len potential issue?

### ISSUE THREAD

**Issue by gyin-ai** [NVIDIA/FasterTransformer#79]
1. request_input_len and max_input_len are hard coded as 1 in tf op gpt. But they are dynamic in pytorch op gpt. If we have start_ids from the context, the gpt tf doesn't take effect now.

https://github.com/NVIDIA/FasterTransformer/blob/93b7751bcbb4b7b29ce647b646baa6414790d4d0/fastertransformer/tf_op/gpt_op.cc#L227

2. can I ask why we still need the min_start_length and max_start_length? I didn't see the usage in tf op while pytorch op didn't require them as input parameters.

**Comment by byshiue** [comment]
1. TF GPT is not a full op, which only support unconditional task. So, user cannot put the contexts in the op and the input length is hence always one.
2. When we have an input context with multiple sentences, we will compute the k/v caches of all sentences by the `min_start_length` in `forward_context`. After that, we will start to run `forward` to generate the tokens. But some tokens are useless because some sentences are longer then `min_start_length`. In this case, we will replace the generated token by the token in the context directly. This checking only happens when `step` <= `max_start_length`.  TensorFlow op does not handle it as the reason of 1. PyTorch op get this information in the op implementation, but not in PyTorch.

**Comment by gyin-ai** [comment]
Can I ask whether we plan to make the tensor flow op similar to pytorch op? It would be useful for use cases like dialoggpt. Thanks

**Comment by byshiue** [comment]
We plan to support it in next version.
